name: Publish Next

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Which package to publish'
        required: true
        type: choice
        options:
          - core
          - crypto
          - entity
          - image
          - nameof
          - nameof-transformer
          - qr
      next:
        description: 'What is the next version e.g. 1 will be appended as -next.1'
        default: 1
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Remove Mono-Repo Node Modules
        run: |
          rm package.json
          rm package-lock.json

      - name: Run Dist
        run: |
          cd packages/${{ github.event.inputs.package }}
          npm install
          npm run dist

      - name: Patch package version
        run: |
          cd packages/${{ github.event.inputs.package }}
          PACKAGE_VERSION=$(cat package.json | jq '.version' | tr -d '"')
          NEXT_VERSION="$PACKAGE_VERSION-next.${{ github.event.inputs.next }}"
          npm pkg set version="$NEXT_VERSION"

      - name: Cleanup package properties
        run: |
          cd packages/${{ github.event.inputs.package }}
          npm pkg delete scripts
          npm pkg delete devDependencies

      - name: Publish
        run: |
          cd packages/${{ github.event.inputs.package }}
          npm publish --access public --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
